import Slot from "../../components/Slot";
export const metadata={title:"Aerospace Quality & Security Certifications | IDAK Aerosystems",description:"Inspect IDAK Aerosystems' published aerospace quality and facility security certificates, including their issuers, scope and validity dates."};
/** @type {Array<[string, string, string, Array<[string, string]>, string, string, string, Array<[string, string]>]>} */
const C=[["01 / Quality management","Aerospace quality management","Issued by BSI Assurance UK Limited",[["Standard / Level","EN 9100:2018 / ISO 9001:2015"],["Valid until","02 January 2027"],["Certificate number","FM 799171"],["Original registration","03 January 2024"]],"/certificates/bsi-en9100-iso9001.png","First page of IDAK's BSI certificate for EN 9100:2018 and ISO 9001:2015","Published scan / page 1 of 2",[["Search BSI directory","https://www.bsigroup.com/en-GB/products-and-services/assessment-and-certification/validation-and-verification/client-directory-certificate/"]]],
["02 / Facility security","Facility security clearance","Issued by Ministry of National Defence of the Republic of Türkiye",[["Standard / Level","MİLLİ GİZLİ / NATIONAL SECRET"],["Valid until","30 March 2027"],["Document number","2022/39"]],"/certificates/facility-security-clearance.png","IDAK facility security clearance certificate issued by Türkiye's Ministry of National Defence","Published scan / single page",[]]];
export default function P(){return(<section><div className="wrap"><h1>Certifications</h1>
{C.map(c=><div className="two cert" key={c[1]}><Slot src={c[4]} alt={c[5]} cap={c[6]} h={420}/><div><p className="kick">{c[0]}</p><h2>{c[1]}</h2><p className="sub">{c[2]}</p>
<dl>{c[3].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><a className="btn" href={c[4]}>Open published scan</a> {c[7].map(([t,u])=><a key={t} className="btn ghost" href={u}>{t}</a>)}</div></div>)}
<p className="sub">Dates and details above are transcribed from the published scans. The issuing authority is the source for current certificate status.</p></div></section>)}
