import Link from "next/link";import Slot from "../../components/Slot";
export const metadata={title:"About IDAK Aerosystems | Aerospace Engineering Expertise",description:"IDAK Aerosystems provides international aerospace engineering and program support from Türkiye, the USA and the UK."};
const V=[["Engineering Excellence","Precision and discipline across design, analysis, manufacturing and qualification."],["Safety & Reliability","Engineering decisions grounded in safe operation, repeatable process and dependable technical data."],["Innovation with Purpose","New methods applied where they improve performance, manufacturability, maintainability or delivery."],["Integrity & Accountability","Transparent, responsible work and accountability for every commitment."],["Partnership & Trust","Long-term technical relationships built through clarity, discretion and delivered value."]];
export default function P(){return(<>
<section><div className="wrap"><p className="kick">About IDAK</p><h1>Aerospace engineering and program support from Türkiye, the USA and the UK.</h1></div></section>
<section className="alt"><div className="wrap"><p className="kick">07 / Program experience</p><h2>Across the aviation landscape.</h2><p className="sub">IDAK works with OEMs, integrators and research organizations in civil aviation, defence aviation, jet trainers, turboprop aircraft, unmanned aerial systems and emerging air mobility.</p>
<p className="sub">IDAK has contributed to localization efforts involving KAAN, HURJET, HURKUS and domestic aircraft engine programs. This experience is presented at the publicly stated program level without implying ownership of complete platforms.</p></div></section>
<section><div className="wrap two"><div><p className="kick">05 / Leadership</p><h2>Experience at program level.</h2><p className="sub">Ali Emre Akgüneş leads IDAK with a focus on engineering delivery, international industrial relationships and practical solutions for aerospace organizations.</p>
<p><b>Ali Emre Akgüneş</b><br/>Chief Executive Officer</p><a className="lnk" href="https://www.aliemreakgunes.com.tr">Visit Personal Website</a></div>
<Slot src="/images/ali-emre-akgunes-primary.jpeg" alt="Ali Emre Akgüneş, Chief Executive Officer of IDAK Aerosystems" h={420}/></div></section>
<section className="alt"><div className="wrap"><p className="kick">How we operate</p><h2>Values expressed in the work.</h2><div className="rows">{V.map(([h,d],i)=><div className="row r3" key={h}><i>0{i+1}</i><h3>{h}</h3><p>{d}</p></div>)}</div></div></section>
<section><div className="wrap"><p className="kick">06 / Quality & security</p><h2>Independent credentials for critical work.</h2><Link className="btn" href="/certificates">View Certifications</Link></div></section></>)}
