import Link from "next/link";import Slot from "../../components/Slot";
export const metadata={title:"Aerospace Engineering Capabilities | IDAK Aerosystems",description:"Structural engineering, aerospace hydraulics, actuation, aircraft harness, avionics, integration and program support from IDAK Aerosystems."};
/** @type {Array<[string, string, string, Array<[string, string, string]>]>} */
const G=[["02 / Aircraft Systems","Aircraft Systems","Hydraulic, electrical and embedded systems engineered from definition through qualification.",[["hydraulics-actuation-systems","Hydraulics & Actuation Systems","Aerospace pumps, reservoirs, valves, accumulators, manifolds, actuators and hydraulic power packages developed through design, analysis, manufacturing, assembly, testing and qualification."],["aircraft-harness-design","Aircraft Harness Design","End-to-end electrical design, 3D routing, documentation and configuration management with standards, risk, installation, EMI, maintainability, manufacturability and certification requirements in view."],["avionics-embedded","Avionics & Embedded Systems","Embedded software engineering for avionics and defence electronics from High Level Requirements through Low Level Requirements and implementation."],["wiring-drafting","3D Wiring & Harness Drafting Support","Skilled wiring drafting capacity for routine aircraft harness, defence wiring and avionics tasks."]]],
["03 / Engineering Delivery","Engineering Delivery","Flexible delivery models aligned to OEM infrastructure, security and program controls.",[["onsite","On-Site Work Integration","IDAK engineers and draftsmen can integrate with OEM teams worldwide while operating under applicable OEM security requirements."],["remote","Remote Site Integration","Remote teams integrate through OEM or IDAK IT infrastructure, with liaison support where appropriate."],["turnkey","Turnkey Integration","Isolated engineering work packages delivered on a turnkey basis with time, budget and quality under coordinated control."]]],
["04 / Business & Program Support","Business & Program Support","Aerospace-focused engineering, consulting, technical procurement and specialist talent support.",[["engineering","Engineering & Design","Aerospace products supported from engineering concept through detailed design and implementation across structures, aircraft systems, avionics, harnesses and hydraulics."],["consulting","Consulting","Infrastructure, processes and tools assessed with aerospace and defence organizations to identify improvement opportunities, share global practice and strengthen performance. IDAK also supports business development by connecting technical requirements with relevant industry opportunities."],["procurement","Procurement Support","IDAK supports aerospace and defence organizations with procurement-related requirements by connecting engineering needs, supply requirements and international industry relationships."],["recruitment","Recruitment","Contract, recruitment-support and permanent recruitment services for manufacturers, MROs, OEMs and related aerospace and defence organizations internationally."]]]];
export default function P(){return(<>
{G.map(([k,t,s,items],n)=><section key={t} className={n===1?"alt":""}><div className="wrap"><p className="kick">{k}</p><h1>{t}</h1><p className="sub">{s}</p>
<div className="rows">{items.map(([id,h,d],i)=><div className="row r3" id={id} key={id}><i>0{i+1}</i><h3>{h}</h3><p>{d}</p></div>)}</div></div></section>)}
<section><div className="wrap two"><div><p className="kick">ATA 29 / Hydraulic power</p><h2>From component definition to qualified system.</h2><p className="sub">IDAK develops aerospace hydraulic and actuation solutions tailored to aircraft, helicopter and engine manufacturer requirements.</p>
<ul>{["Design","Analysis","Manufacturing","Assembly","Testing","Qualification"].map((x,i)=><li key={x}>0{i+1} {x}</li>)}</ul><p><Link className="lnk" href="/certificates">View Certifications</Link></p></div>
<Slot src="/images/editorial/hydraulic-components.jpg" alt="Five aerospace hydraulic components arranged for inspection" cap="Hydraulic components 02 / Hardware detail" h={340}/></div></section>
<section className="alt"><div className="wrap"><p className="kick">Aircraft harness design</p><h2>Experience routed through the aircraft.</h2>
<div className="g3 stats2"><div><b>180,000+</b><span>hours of harness design experience</span></div><div><b>5</b><span>aircraft platforms</span></div></div>
<p className="sub">Electrical design. 3D routing. Documentation. Configuration management. Standards-driven design, risk assessment and installation constraints—with EMI, maintainability, manufacturability and certification requirements in view.</p>
<div className="two" style={{marginTop:32}}><Slot src="/images/editorial/avionics-cockpit.jpg" alt="Aircraft flight deck with integrated avionics displays" cap="03 / Flight deck context"/><Slot src="/images/editorial/aircraft-harness.jpeg" alt="Routed cable harnesses inside an aircraft structure" cap="04 / Aircraft cable routing"/></div></div></section>
<section><div className="wrap"><p className="kick">Business principles</p><h2>Clear terms. Protected work.</h2><div className="g3 cards" style={{gridTemplateColumns:"repeat(2,1fr)"}}>
{[["Fair engagement","IDAK does not charge partners, candidates or third parties for initial contacts and services as described in its public business principles."],["Conflicts & compensation","IDAK seeks to avoid conflicts of interest. Compensation is tied to fulfilling partner requirements."],["Applicable law","IDAK follows the laws of the countries where it operates and does not ask questions prohibited by applicable jurisdictions."],["Project confidentiality","Non-disclosure agreements can be established where required to protect project information and collaboration."]].map(([h,d])=><div key={h} className="bx"><h3>{h}</h3><p>{d}</p></div>)}</div></div></section></>)}
